In [1]:
import torch

## 2.1.1 入门

张量表示一个由数值组成的数组，这个数组可能有多个维度。 具有一个轴的张量对应数学上的向量（vector）； 具有两个轴的张量对应数学上的矩阵（matrix）； 具有两个轴以上的张量没有特殊的数学名称。

使用arange创建一个从0到11的行向量，此外还可用`dtype`指定数据的类型

```
新的张量将存储在内存中，并采用基于CPU的计算。
```

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
# 张量中所有元素的总数
x.numel()

12

In [5]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
X = x.reshape(-1, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

从特定概率分布中随机采样获得张量元素

In [9]:
# 均值为0，标准差为1的高斯分布
torch.randn(3, 4)

tensor([[ 1.9022, -1.1756,  0.9087,  0.2979],
        [-1.0865,  1.3459, -1.5206, -0.9335],
        [ 1.0254, -1.1284,  0.4919, -1.1412]])

python嵌套列表转为张量

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 运算符

按元素运算(elementwise)：每个位置对应进行计算

In [12]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [13]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

张量的拼接

In [15]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]))

In [20]:
# 按行拼接（理解为在行上进行变化）
torch.cat((X, Y), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])

In [21]:
# 按列拼接（理解为在列上进行变化）
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [23]:
# 如果为三个维度会怎么样？
X = torch.arange(12, dtype=torch.float32).reshape((2, 3, 2))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).reshape((2, 3, 2))
X, Y

(tensor([[[ 0.,  1.],
          [ 2.,  3.],
          [ 4.,  5.]],
 
         [[ 6.,  7.],
          [ 8.,  9.],
          [10., 11.]]]),
 tensor([[[2., 1.],
          [4., 3.],
          [1., 2.]],
 
         [[3., 4.],
          [4., 3.],
          [2., 1.]]]))

In [27]:
torch.cat((X, Y), dim=0).shape

torch.Size([4, 3, 2])

In [26]:
torch.cat((X, Y), dim=1).shape

torch.Size([2, 6, 2])

In [28]:
torch.cat((X, Y), dim=2).shape

torch.Size([2, 3, 4])

逻辑运算符构建二元张量

In [30]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

求和

In [32]:
X.sum(dim=0), X.sum(dim=1), X.sum()

(tensor([12., 15., 18., 21.]), tensor([ 6., 22., 38.]), tensor(66.))

## 2.1.3 广播机制

1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；

2. 对生成的数组执行按元素操作。

In [35]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, a.shape, b, b.shape

(tensor([[0],
         [1],
         [2]]),
 torch.Size([3, 1]),
 tensor([[0, 1]]),
 torch.Size([1, 2]))

由于a和b分别是$3 \times 1$和$1 \times 2$矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的$3\times2$矩阵，如下所示：
矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

In [34]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引和切片

In [41]:
# 取最后一行；取第2行第4列
X, X[-1], X[1:3]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

指定位置为某值

In [42]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。

In [43]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 节省内存

运行一些操作可能会导致为新结果分配内存。 例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [44]:
before = id(Y)
Y = Y + X
id(Y) == before

False

这可能是不可取的，原因有两个：

1. 首先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在一秒内多次更新所有参数。通常情况下，我们希望原地执行这些更新；

2. 如果我们不原地更新，__其他引用仍然会指向旧的内存位置__，这样我们的某些代码可能会无意中引用旧的参数。

使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>。

In [45]:
# 分配一个和Y形状一样的全0张量
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 4655530448
id(Z): 4655530448


如果在后续计算中没有重复使用X， 我们也可以使用X[:] = X + Y或X += Y来减少操作的内存开销。

In [46]:
before = id(X)
X += Y
id(X) == before

True

## 2.1.6 转换为其他Python对象

In [47]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为Python标量，我们可以调用item函数或Python的内置函数。

In [48]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习

用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [57]:
t1 = torch.arange(4).reshape((1, 1, 4))
t2 = torch.tensor([2, 2]).reshape((1, 2, 1))
t1, t2

(tensor([[[0, 1, 2, 3]]]),
 tensor([[[2],
          [2]]]))

In [59]:
(t1 + t2).shape

torch.Size([1, 2, 4])

In [60]:
t3 = torch.arange(4).reshape((4, 1, 1))
t4 = torch.tensor([2, 2]).reshape((1, 2, 1))
t3, t4

(tensor([[[0]],
 
         [[1]],
 
         [[2]],
 
         [[3]]]),
 tensor([[[2],
          [2]]]))

In [63]:
(t3 + t4)

tensor([[[2],
         [2]],

        [[3],
         [3]],

        [[4],
         [4]],

        [[5],
         [5]]])